import { MaterialCategory, PriceBenchmark, RecyclerProfile, ScrapLot, SafetyTip } from './types'

export const MATERIAL_CATEGORIES: {
  id: MaterialCategory
  icon: string
  labelKey: string
  color: string
  avgPrice: number
  sampleImage: string
}[] = [
  {
    id: 'pcb',
    icon: '🟩',
    labelKey: 'cat_pcb',
    color: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    avgPrice: 220,
    sampleImage: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'cables',
    icon: '🔌',
    labelKey: 'cat_cables',
    color: 'bg-amber-100 text-amber-800 border-amber-300',
    avgPrice: 180,
    sampleImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'batteries',
    icon: '🔋',
    labelKey: 'cat_batteries',
    color: 'bg-blue-100 text-blue-800 border-blue-300',
    avgPrice: 95,
    sampleImage: 'https://images.unsplash.com/photo-1619641782821-75178523cf44?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'lcd',
    icon: '📺',
    labelKey: 'cat_lcd',
    color: 'bg-indigo-100 text-indigo-800 border-indigo-300',
    avgPrice: 120,
    sampleImage: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'crt',
    icon: '📺',
    labelKey: 'cat_crt',
    color: 'bg-slate-100 text-slate-800 border-slate-300',
    avgPrice: 45,
    sampleImage: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'motors',
    icon: '⚙️',
    labelKey: 'cat_motors',
    color: 'bg-stone-100 text-stone-800 border-stone-300',
    avgPrice: 75,
    sampleImage: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'magnets',
    icon: '🧲',
    labelKey: 'cat_magnets',
    color: 'bg-rose-100 text-rose-800 border-rose-300',
    avgPrice: 60,
    sampleImage: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'plastic',
    icon: '♻️',
    labelKey: 'cat_plastic',
    color: 'bg-teal-100 text-teal-800 border-teal-300',
    avgPrice: 38,
    sampleImage: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'metal',
    icon: '🔩',
    labelKey: 'cat_metal',
    color: 'bg-zinc-100 text-zinc-800 border-zinc-300',
    avgPrice: 110,
    sampleImage: 'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?auto=format&fit=crop&w=600&q=80',
  },
]

export const BENCHMARK_PRICES: PriceBenchmark[] = [
  {
    category: 'pcb',
    name: 'Printed Circuit Boards (PCB)',
    currentPrice: 220,
    minPrice: 200,
    maxPrice: 240,
    trend: 4.5,
    unit: 'kg',
    lastUpdated: 'Today',
  },
  {
    category: 'cables',
    name: 'Insulated Copper Cables',
    currentPrice: 180,
    minPrice: 170,
    maxPrice: 195,
    trend: 2.8,
    unit: 'kg',
    lastUpdated: 'Today',
  },
  {
    category: 'batteries',
    name: 'Lead-Acid & Li-Ion Batteries',
    currentPrice: 95,
    minPrice: 85,
    maxPrice: 105,
    trend: -1.2,
    unit: 'kg',
    lastUpdated: 'Today',
  },
  {
    category: 'lcd',
    name: 'LCD / LED Display Panels',
    currentPrice: 120,
    minPrice: 110,
    maxPrice: 135,
    trend: 1.5,
    unit: 'kg',
    lastUpdated: 'Today',
  },
  {
    category: 'crt',
    name: 'CRT Glass & Monitor Housings',
    currentPrice: 45,
    minPrice: 40,
    maxPrice: 50,
    trend: 0.0,
    unit: 'kg',
    lastUpdated: 'Today',
  },
  {
    category: 'motors',
    name: 'Electric Motors & Stators',
    currentPrice: 75,
    minPrice: 70,
    maxPrice: 82,
    trend: 3.1,
    unit: 'kg',
    lastUpdated: 'Today',
  },
  {
    category: 'magnets',
    name: 'Ferrite & Neodymium Magnets',
    currentPrice: 60,
    minPrice: 55,
    maxPrice: 68,
    trend: -0.5,
    unit: 'kg',
    lastUpdated: 'Today',
  },
  {
    category: 'plastic',
    name: 'Mixed E-Waste Plastics (ABS/HIPS)',
    currentPrice: 38,
    minPrice: 35,
    maxPrice: 42,
    trend: 1.8,
    unit: 'kg',
    lastUpdated: 'Today',
  },
]

// Recyclers centered around Sangli, Maharashtra (coordinates approx: 16.8524, 74.5815)
export const INITIAL_RECYCLERS: RecyclerProfile[] = [
  {
    id: 'rec-001',
    facilityName: 'ABC E-Waste Recycling Pvt Ltd',
    ownerName: 'Rajesh Patil',
    phone: '+91 98220 11234',
    email: 'contact@abcewaste.co.in',
    address: 'Plot No. 44, MIDC Kupwad, Sangli, Maharashtra 416436',
    city: 'Sangli',
    state: 'Maharashtra',
    coordinates: [16.8654, 74.6142],
    distanceKm: 8,
    authorizationNo: 'MPCB/RO-SGL/E-WASTE/2024/0891',
    issuingAuthority: 'MPCB',
    verificationStatus: 'verified',
    verificationDate: '15 Jan 2024',
    validTill: '31 Dec 2028',
    pickupAvailable: true,
    serviceRadiusKm: 50,
    rating: 4.8,
    totalTransactions: 342,
    capacityTonsPerYear: 2400,
    verifiedBadge: true,
    description: 'CPCB and MPCB certified green e-waste dismantler with mechanized shredding, precious metal recovery ties and formal transfer manifests.',
    rates: {
      pcb: { category: 'pcb', ratePerKg: 225, minQuantityKg: 5, lastUpdated: 'Today', effectiveFrom: '01 Sep 2026', accepted: true },
      cables: { category: 'cables', ratePerKg: 185, minQuantityKg: 10, lastUpdated: 'Today', effectiveFrom: '01 Sep 2026', accepted: true },
      batteries: { category: 'batteries', ratePerKg: 98, minQuantityKg: 10, lastUpdated: 'Today', effectiveFrom: '01 Sep 2026', accepted: true },
      lcd: { category: 'lcd', ratePerKg: 125, minQuantityKg: 5, lastUpdated: 'Today', effectiveFrom: '01 Sep 2026', accepted: true },
      crt: { category: 'crt', ratePerKg: 46, minQuantityKg: 10, lastUpdated: 'Today', effectiveFrom: '01 Sep 2026', accepted: true },
      motors: { category: 'motors', ratePerKg: 78, minQuantityKg: 10, lastUpdated: 'Today', effectiveFrom: '01 Sep 2026', accepted: true },
      magnets: { category: 'magnets', ratePerKg: 62, minQuantityKg: 5, lastUpdated: 'Today', effectiveFrom: '01 Sep 2026', accepted: true },
      plastic: { category: 'plastic', ratePerKg: 40, minQuantityKg: 20, lastUpdated: 'Today', effectiveFrom: '01 Sep 2026', accepted: true },
      metal: { category: 'metal', ratePerKg: 115, minQuantityKg: 10, lastUpdated: 'Today', effectiveFrom: '01 Sep 2026', accepted: true },
    },
  },
  {
    id: 'rec-002',
    facilityName: 'Maharashtra Eco-Cyclers Hub',
    ownerName: 'Sunil Deshmukh',
    phone: '+91 94224 55678',
    email: 'info@mahaecocyclers.org',
    address: 'Industrial Estate, Near Railway Gate, Miraj, Maharashtra 416410',
    city: 'Miraj',
    state: 'Maharashtra',
    coordinates: [16.8285, 74.6534],
    distanceKm: 14,
    authorizationNo: 'MPCB/E-WASTE/R-2490',
    issuingAuthority: 'MPCB',
    verificationStatus: 'verified',
    verificationDate: '10 Aug 2023',
    validTill: '09 Aug 2027',
    pickupAvailable: true,
    serviceRadiusKm: 60,
    rating: 4.7,
    totalTransactions: 215,
    capacityTonsPerYear: 1800,
    verifiedBadge: true,
    description: 'Specialized in telecom, IT scrap, high grade PCB boards and heavy copper windings. Same day digital weighbridge and immediate UPI payout.',
    rates: {
      pcb: { category: 'pcb', ratePerKg: 215, minQuantityKg: 10, lastUpdated: 'Today', effectiveFrom: '28 Aug 2026', accepted: true },
      cables: { category: 'cables', ratePerKg: 182, minQuantityKg: 15, lastUpdated: 'Today', effectiveFrom: '28 Aug 2026', accepted: true },
      batteries: { category: 'batteries', ratePerKg: 102, minQuantityKg: 15, lastUpdated: 'Today', effectiveFrom: '28 Aug 2026', accepted: true },
      lcd: { category: 'lcd', ratePerKg: 118, minQuantityKg: 5, lastUpdated: 'Today', effectiveFrom: '28 Aug 2026', accepted: true },
      crt: { category: 'crt', ratePerKg: 42, minQuantityKg: 10, lastUpdated: 'Today', effectiveFrom: '28 Aug 2026', accepted: false },
      motors: { category: 'motors', ratePerKg: 80, minQuantityKg: 10, lastUpdated: 'Today', effectiveFrom: '28 Aug 2026', accepted: true },
      magnets: { category: 'magnets', ratePerKg: 58, minQuantityKg: 10, lastUpdated: 'Today', effectiveFrom: '28 Aug 2026', accepted: true },
      plastic: { category: 'plastic', ratePerKg: 38, minQuantityKg: 25, lastUpdated: 'Today', effectiveFrom: '28 Aug 2026', accepted: true },
      metal: { category: 'metal', ratePerKg: 112, minQuantityKg: 10, lastUpdated: 'Today', effectiveFrom: '28 Aug 2026', accepted: true },
    },
  },
  {
    id: 'rec-003',
    facilityName: 'Krishna CleanTech Facilities',
    ownerName: 'Vikram Joshi',
    phone: '+91 97631 88901',
    email: 'care@krishnacleantech.com',
    address: 'Survey 112, Kupwad-Tasgaon Road, Sangli, Maharashtra 416436',
    city: 'Sangli',
    state: 'Maharashtra',
    coordinates: [16.8821, 74.5982],
    distanceKm: 6,
    authorizationNo: 'MPCB/EW/2023/1104',
    issuingAuthority: 'MPCB',
    verificationStatus: 'verified',
    verificationDate: '02 Feb 2024',
    validTill: '01 Feb 2029',
    pickupAvailable: true,
    serviceRadiusKm: 40,
    rating: 4.9,
    totalTransactions: 410,
    capacityTonsPerYear: 3200,
    verifiedBadge: true,
    description: 'Advanced automated sorting plant with highest spot prices for motherboards, RAM sticks, processors, and clean copper cable bundles.',
    rates: {
      pcb: { category: 'pcb', ratePerKg: 228, minQuantityKg: 5, lastUpdated: 'Yesterday', effectiveFrom: '01 Sep 2026', accepted: true },
      cables: { category: 'cables', ratePerKg: 188, minQuantityKg: 8, lastUpdated: 'Yesterday', effectiveFrom: '01 Sep 2026', accepted: true },
      batteries: { category: 'batteries', ratePerKg: 96, minQuantityKg: 10, lastUpdated: 'Yesterday', effectiveFrom: '01 Sep 2026', accepted: true },
      lcd: { category: 'lcd', ratePerKg: 122, minQuantityKg: 5, lastUpdated: 'Yesterday', effectiveFrom: '01 Sep 2026', accepted: true },
      crt: { category: 'crt', ratePerKg: 48, minQuantityKg: 5, lastUpdated: 'Yesterday', effectiveFrom: '01 Sep 2026', accepted: true },
      motors: { category: 'motors', ratePerKg: 76, minQuantityKg: 10, lastUpdated: 'Yesterday', effectiveFrom: '01 Sep 2026', accepted: true },
      magnets: { category: 'magnets', ratePerKg: 64, minQuantityKg: 5, lastUpdated: 'Yesterday', effectiveFrom: '01 Sep 2026', accepted: true },
      plastic: { category: 'plastic', ratePerKg: 42, minQuantityKg: 15, lastUpdated: 'Yesterday', effectiveFrom: '01 Sep 2026', accepted: true },
      metal: { category: 'metal', ratePerKg: 118, minQuantityKg: 10, lastUpdated: 'Yesterday', effectiveFrom: '01 Sep 2026', accepted: true },
    },
  },
  {
    id: 'rec-004',
    facilityName: 'Western Ghats Resource Recovery',
    ownerName: 'Anil Kadam',
    phone: '+91 98900 33421',
    email: 'admin@wgresourcerecovery.in',
    address: 'Shiroli MIDC, Kolhapur Road, Maharashtra 416122',
    city: 'Kolhapur',
    state: 'Maharashtra',
    coordinates: [16.7410, 74.3210],
    distanceKm: 38,
    authorizationNo: 'MPCB/EW-REG/9082',
    issuingAuthority: 'MPCB',
    verificationStatus: 'verified',
    verificationDate: '12 Nov 2023',
    validTill: '11 Nov 2027',
    pickupAvailable: true,
    serviceRadiusKm: 80,
    rating: 4.6,
    totalTransactions: 180,
    capacityTonsPerYear: 1500,
    verifiedBadge: true,
    description: 'Regional recycling depot accepting bulk industrial e-scrap, power supplies, CRT de-manufacturing with complete lead trap safety.',
    rates: {
      pcb: { category: 'pcb', ratePerKg: 218, minQuantityKg: 20, lastUpdated: '3 days ago', effectiveFrom: '20 Aug 2026', accepted: true },
      cables: { category: 'cables', ratePerKg: 180, minQuantityKg: 25, lastUpdated: '3 days ago', effectiveFrom: '20 Aug 2026', accepted: true },
      batteries: { category: 'batteries', ratePerKg: 94, minQuantityKg: 20, lastUpdated: '3 days ago', effectiveFrom: '20 Aug 2026', accepted: true },
      lcd: { category: 'lcd', ratePerKg: 115, minQuantityKg: 10, lastUpdated: '3 days ago', effectiveFrom: '20 Aug 2026', accepted: true },
      crt: { category: 'crt', ratePerKg: 45, minQuantityKg: 15, lastUpdated: '3 days ago', effectiveFrom: '20 Aug 2026', accepted: true },
      motors: { category: 'motors', ratePerKg: 75, minQuantityKg: 20, lastUpdated: '3 days ago', effectiveFrom: '20 Aug 2026', accepted: true },
      magnets: { category: 'magnets', ratePerKg: 60, minQuantityKg: 10, lastUpdated: '3 days ago', effectiveFrom: '20 Aug 2026', accepted: true },
      plastic: { category: 'plastic', ratePerKg: 37, minQuantityKg: 50, lastUpdated: '3 days ago', effectiveFrom: '20 Aug 2026', accepted: true },
      metal: { category: 'metal', ratePerKg: 108, minQuantityKg: 25, lastUpdated: '3 days ago', effectiveFrom: '20 Aug 2026', accepted: true },
    },
  },
  {
    id: 'rec-005',
    facilityName: 'Sahyadri Dismantlers & Scrap Yard',
    ownerName: 'Ganesh More',
    phone: '+91 93701 44556',
    email: 'sahyadri.scrap@gmail.com',
    address: 'Old Miraj Road, Sangli, Maharashtra 416416',
    city: 'Sangli',
    state: 'Maharashtra',
    coordinates: [16.8410, 74.6110],
    distanceKm: 3.5,
    authorizationNo: 'CPCB/AUDIT-PENDING/8821',
    issuingAuthority: 'CPCB',
    verificationStatus: 'pending',
    verificationDate: 'Under Review',
    validTill: 'Provisional 2026',
    pickupAvailable: false,
    serviceRadiusKm: 15,
    rating: 4.1,
    totalTransactions: 65,
    capacityTonsPerYear: 600,
    verifiedBadge: false,
    description: 'Local collection center upgrading to authorized dismantler status. Drop-off only.',
    rates: {
      pcb: { category: 'pcb', ratePerKg: 205, minQuantityKg: 5, lastUpdated: 'Today', effectiveFrom: '01 Sep 2026', accepted: true },
      cables: { category: 'cables', ratePerKg: 172, minQuantityKg: 5, lastUpdated: 'Today', effectiveFrom: '01 Sep 2026', accepted: true },
      batteries: { category: 'batteries', ratePerKg: 88, minQuantityKg: 5, lastUpdated: 'Today', effectiveFrom: '01 Sep 2026', accepted: true },
      lcd: { category: 'lcd', ratePerKg: 110, minQuantityKg: 2, lastUpdated: 'Today', effectiveFrom: '01 Sep 2026', accepted: true },
      crt: { category: 'crt', ratePerKg: 40, minQuantityKg: 5, lastUpdated: 'Today', effectiveFrom: '01 Sep 2026', accepted: true },
      motors: { category: 'motors', ratePerKg: 70, minQuantityKg: 5, lastUpdated: 'Today', effectiveFrom: '01 Sep 2026', accepted: true },
      magnets: { category: 'magnets', ratePerKg: 55, minQuantityKg: 5, lastUpdated: 'Today', effectiveFrom: '01 Sep 2026', accepted: true },
      plastic: { category: 'plastic', ratePerKg: 35, minQuantityKg: 10, lastUpdated: 'Today', effectiveFrom: '01 Sep 2026', accepted: true },
      metal: { category: 'metal', ratePerKg: 102, minQuantityKg: 5, lastUpdated: 'Today', effectiveFrom: '01 Sep 2026', accepted: true },
    },
  },
]

export const INITIAL_SCRAP_LOTS: ScrapLot[] = [
  {
    id: 'KC-2026-000124',
    collectorId: 'usr-kaba-01',
    collectorName: 'Ramesh Shinde',
    collectorPhone: '+91 98231 44099',
    category: 'pcb',
    subCategory: 'Computer Motherboard / Green PCB',
    condition: 'good',
    declaredWeightKg: 10,
    verifiedWeightKg: 10.2,
    estimatedMinPrice: 2000,
    estimatedMaxPrice: 2400,
    quotedPrice: 2200,
    finalPrice: 2295,
    photoUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=600&q=80',
    aiConfidence: 87,
    aiDetectedMaterial: 'High-Grade Printed Circuit Board (Motherboard)',
    status: 'completed',
    createdAt: '2026-09-07 09:30 AM',
    updatedAt: '2026-09-07 02:45 PM',
    location: 'Market Yard, Sangli, Maharashtra',
    coordinates: [16.8524, 74.5815],
    recyclerId: 'rec-001',
    recyclerName: 'ABC E-Waste Recycling Pvt Ltd',
    paymentMethod: 'CASH',
    paymentStatus: 'PAID',
    isOfflineDraft: false,
    notes: 'Grade A computer boards, sorted and clean from dust.',
  },
  {
    id: 'KC-2026-000125',
    collectorId: 'usr-kaba-01',
    collectorName: 'Ramesh Shinde',
    collectorPhone: '+91 98231 44099',
    category: 'cables',
    subCategory: 'Insulated Pure Copper Wiring',
    condition: 'good',
    declaredWeightKg: 25,
    estimatedMinPrice: 4250,
    estimatedMaxPrice: 4875,
    quotedPrice: 4500,
    photoUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80',
    aiConfidence: 94,
    aiDetectedMaterial: 'Heavy Insulated Copper Wire Harness',
    status: 'recycler_requested',
    createdAt: '2026-09-08 08:15 AM',
    updatedAt: '2026-09-08 08:30 AM',
    location: 'Miraj Road Depot, Sangli',
    coordinates: [16.8450, 74.6050],
    recyclerId: 'rec-001',
    recyclerName: 'ABC E-Waste Recycling Pvt Ltd',
    paymentStatus: 'PENDING',
    isOfflineDraft: false,
    notes: 'Telecommunication and heavy power cable cutoffs.',
  },
  {
    id: 'KC-2026-000126',
    collectorId: 'usr-kaba-01',
    collectorName: 'Ramesh Shinde',
    collectorPhone: '+91 98231 44099',
    category: 'batteries',
    subCategory: 'UPS Inverter Sealed Lead Acid',
    condition: 'used',
    declaredWeightKg: 18,
    estimatedMinPrice: 1530,
    estimatedMaxPrice: 1890,
    quotedPrice: 1710,
    photoUrl: 'https://images.unsplash.com/photo-1619641782821-75178523cf44?auto=format&fit=crop&w=600&q=80',
    aiConfidence: 91,
    aiDetectedMaterial: 'Sealed Lead Acid Storage Battery (VRLA)',
    status: 'lot_created',
    createdAt: '2026-09-08 10:00 AM',
    updatedAt: '2026-09-08 10:00 AM',
    location: 'Ganpati Peth, Sangli',
    coordinates: [16.8570, 74.5750],
    paymentStatus: 'UNPAID',
    isOfflineDraft: false,
    notes: 'No acid leak, contact terminals safely isolated.',
  },
]

export const SAFETY_TIPS: SafetyTip[] = [
  {
    id: 'cables_burn',
    icon: '🔥',
    severity: 'critical',
    title: {
      en: "Don't Burn Cables",
      hi: 'तारों को कभी न जलाएं!',
      mr: 'केबल किंवा वायर जाळू नका!',
    },
    hazard: {
      en: 'Burning PVC and insulation releases toxic dioxins, furans, and black smoke that permanently damage lungs and cause cancer. Copper recovered by burning is degraded in quality and fetches lower market price.',
      hi: 'पीवीसी या रबर केबल जलाने से निकलने वाला काला धुआं फेफड़ों को भारी नुकसान पहुंचाता है और कैंसर का कारण बनता है। जला हुआ तांबा काला पड़ जाता है और उसका बाजार में कम दाम मिलता है।',
      mr: 'प्लास्टिक किंवा वायर जाळल्याने अत्यंत विषारी वायू बाहेर पडतो ज्याने कर्करोग व दम्याचा आजार होतो. जाळलेल्या तांब्याचा दर्जा घसरतो आणि रिसायकलर कमी भाव देतात.',
    },
    safeAlternative: {
      en: 'Use a handheld mechanical wire stripper ($1.50 tool) or sell insulated cables directly as-is to authorized recyclers who have automated cable granulators.',
      hi: 'हाथ से चलने वाले सस्ते वायर स्ट्रिपर का उपयोग करें या तारों को बिना छीले सीधे अधिकृत रिसाइक्लिंग केंद्रों पर बेचें, जहाँ ऑटोमैटिक मशीनें होती हैं।',
      mr: 'साधे वायर स्ट्रिपर वापरा किंवा केबल न कापता थेट अधिकृत रिसायकलरला विका, ज्यांच्याकडे अत्याधुनिक ग्रॅन्युलेटर मशिन असते.',
    },
    audioText: {
      en: 'Warning: Never burn scrap cables. The burning plastic releases deadly cancer-causing dioxin gases. Always strip cables mechanically or sell insulated wire directly to authorized recyclers for a higher fair price.',
      hi: 'चेतावनी: कबाड़ के तारों को कभी न जलाएं। तार जलाने से जानलेवा कैंसर कारक गैसें निकलती हैं। तारों को वायर स्ट्रिपर से छीलें या सीधे अधिकृत रिसाइक्लिंग केंद्र को सही दाम पर बेचें।',
      mr: 'सावधान: भंगारातील केबल कधीही जाळू नका. प्लास्टिक जाळल्याने कर्करोग करणारे विषारी वायू निघतात. वायर स्ट्रिपर वापरा किंवा थेट अधिकृत केंद्राला चांगल्या भावात विका.',
    },
  },
  {
    id: 'acid_leach',
    icon: '🧪',
    severity: 'critical',
    title: {
      en: "Don't Use Acid to Extract Metals",
      hi: 'तेजाब / एसिड का उपयोग न करें!',
      mr: 'पीसीबीवर अ‍ॅसिड किंवा तेजाब वापरू नका!',
    },
    hazard: {
      en: 'Using nitric acid or cyanide to leach gold and silver produces toxic nitrogen dioxide gases that burn throat and eyes, and hazardous liquid waste contaminates village groundwater.',
      hi: 'पीसीबी से सोना-चांदी निकालने के लिए नाइट्रिक एसिड या सायनाइड का उपयोग आंखों और फेफड़ों को जला देता है। जहरीला तेजाब जमीन में मिलकर पीने के पानी को जहरीला कर देता है।',
      mr: 'सोनं काढण्यासाठी पीसीबीवर अ‍ॅसिड किंवा तेजाब वापरल्याने प्राणघातक विषारी वायू तयार होतो. हे पाणी जमिनीत मुरून गावातील पिण्याचे पाणी विषारी होते.',
    },
    safeAlternative: {
      en: 'Authorized recyclers use closed-loop hydrometallurgy facilities that achieve 99% gold recovery without any toxic exposure and pay you upfront.',
      hi: 'अधिकृत रिसाइक्लिंग संयंत्र आधुनिक तकनीक से 99% तक धातु सुरक्षित निकालते हैं और आपको बिना किसी खतरे के तुरंत पूरा पैसा देते हैं।',
      mr: 'अधिकृत रिसायकलर्स आधुनिक बंद यंत्रणेद्वारे सुरक्षितपणे मौल्यवान धातू वेगळे करतात आणि तुम्हाला लगेच रोख किंवा बँक खात्यात पैसे देतात.',
    },
    audioText: {
      en: 'Warning: Do not use acid or chemicals on circuit boards. Acid fumes burn your respiratory system. Sell intact boards to authorized recyclers who give you transparent weighing and market rates.',
      hi: 'चेतावनी: सर्किट बोर्ड पर कभी तेजाब या रसायन न डालें। इसके धुएं से फेफड़े जल सकते हैं। पूरे बोर्ड को अधिकृत रिसाइक्लिंग केंद्र को बेचें और सुरक्षित रहें।',
      mr: 'सावधान: सर्किट बोर्डवर कधीही अ‍ॅसिड टाकू नका. त्याचे विषारी वाफ फुफ्फुसांना जाळते. संपूर्ण बोर्ड अधिकृत केंद्राला देऊन योग्य भाव मिळवा.',
    },
  },
  {
    id: 'battery_puncture',
    icon: '🔋',
    severity: 'high',
    title: {
      en: 'Battery Safety & Storage',
      hi: 'बैटरी को कभी न तोड़ें या काटें!',
      mr: 'बॅटरी कापू किंवा फोडू नका!',
    },
    hazard: {
      en: 'Lithium-ion cells experience thermal runaway when punctured, releasing flames up to 600°C within seconds. Lead-acid batteries contain caustic sulfuric acid.',
      hi: 'लिथियम बैटरी पर हथौड़ा या चोट लगने पर वह सेकंडों में 600 डिग्री तक आग पकड़ लेती है। इनवर्टर बैटरी में खतरनाक सल्फ्यूरिक एसिड होता है।',
      mr: 'लिथियम आणि मोबाईल बॅटरी फुटल्यास सेकंदात भयंकर आग लागते. इनव्हर्टरच्या बॅटरीमध्ये जहाल सल्फ्यूरिक अ‍ॅसिड असते जे अंगावर उडू शकते.',
    },
    safeAlternative: {
      en: 'Cover open battery terminals with regular electrical insulation tape. Store inside a sturdy plastic bin away from direct sunlight and moisture.',
      hi: 'बैटरी के दोनों सिरों पर इंसुलेशन टेप चिपकाएं। इन्हें सूखी और ठंडी जगह पर अलग प्लास्टिक के डिब्बे में रखें।',
      mr: 'बॅटरीच्या टोकांवर नेहमी इन्सुलेशन टेप लावा. बॅटऱ्या कोरड्या आणि सुरक्षित प्लास्टिकच्या डब्यात वेगळ्या साठवा.',
    },
    audioText: {
      en: 'Battery safety advisory: Never hit or break open batteries. Insulate the terminals with tape to prevent short circuits and catastrophic fire. Sell safely to licensed battery recyclers.',
      hi: 'बैटरी सुरक्षा सलाह: बैटरी पर कभी हथौड़ा न चलाएं। शॉर्ट सर्किट रोकने के लिए सिरों पर टेप लगाएं और केवल लाइसेंस प्राप्त रिसाइक्लर को ही दें।',
      mr: 'बॅटरी सुरक्षा सूचना: बॅटरी कधीही हातोड्याने फोडू नका. शॉर्ट सर्किट टाळण्यासाठी दोन्ही टोकांवर टेप लावा आणि अधिकृत केंद्रातच जमा करा.',
    },
  },
  {
    id: 'crt_implosion',
    icon: '📺',
    severity: 'warning',
    title: {
      en: 'CRT Glass Handling Caution',
      hi: 'सीआरटी मॉनिटर कांच न फोड़ें!',
      mr: 'सीआरटी मॉनिटरची काच फोडू नका!',
    },
    hazard: {
      en: 'Cathode ray tube funnel glass contains up to 2-3 kg of hazardous lead oxide. Breaking the glass creates vacuum implosion projecting glass shards up to 10 meters.',
      hi: 'पुराने टीवी और मॉनिटर ट्यूब में 2 से 3 किलो तक जहरीला लेड (सीसा) होता है। इसके टूटने पर निर्वात दबाव के कारण कांच के टुकड़े 10 मीटर तक उड़ते हैं।',
      mr: 'जुन्या टीव्हीच्या ट्यूबमध्ये २ ते ३ किलो विषारी शिसे असते. ही काच फुटल्यास प्रचंड वेगाने काचेचे तुकडे उडून डोळे किंवा चेहऱ्याला गंभीर इजा होऊ शकते.',
    },
    safeAlternative: {
      en: 'Keep CRT units intact in their original plastic or wooden frames during transport. Authorized recyclers safely separate the lead funnel glass in negative-pressure chambers.',
      hi: 'सीआरटी मॉनिटर को प्लास्टिक कैबिनेट के अंदर सुरक्षित रखें। अधिकृत रिसाइक्लिंग केंद्रों पर इसे खास सुरक्षा चैंबर में अलग किया जाता है।',
      mr: 'सीआरटी मॉनिटर नेहमी प्लास्टिकच्या कव्हरमध्येच सुरक्षित ठेवा. अधिकृत केंद्रात खास व्हॅक्यूम चेंबरमध्ये शिसे सुरक्षितपणे वेगळे केले जाते.',
    },
    audioText: {
      en: 'CRT caution: Never break television tubes. They contain hazardous heavy lead and risk vacuum implosion. Transport intact to an authorized facility.',
      hi: 'सीआरटी सावधानी: टीवी या कंप्यूटर ट्यूब को कभी न तोड़ें। इसमें जहरीला लेड होता है। इसे बिना तोड़े सीधे अधिकृत केंद्र पर पहुंचाएं।',
      mr: 'सीआरटी खबरदारी: टीव्ही मॉनिटरची ट्यूब कधीही फोडू नका. यात विषारी शिसे असते. ती अखंड ठेवूनच अधिकृत केंद्रात जमा करा.',
    },
  },
]
